const records=[['TUT-2026-10482','Lerato Mokoena','Diploma in Information Technology','Active'],['UL-2025-77821','Thabo Ndlovu','BSc Computer Science','Active'],['UNIVEN-2024-32017','Naledi Mathonsi','BCom','Active']];
const audits=[['Demo start','SYSTEM','Demo environment initialised']];
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));render();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function simulateOCR(){const f=document.getElementById('file').files[0]; if(!f){alert('Please choose a certificate file first.');return;} document.getElementById('uploadBox').classList.add('hidden');document.getElementById('reviewBox').classList.remove('hidden');audits.unshift([new Date().toLocaleString(),'Verification Officer','Certificate uploaded; simulated OCR completed']);render();}
function runVerification(){document.getElementById('reviewBox').classList.add('hidden');const p=document.getElementById('progressBox');p.classList.remove('hidden');const steps=['Cross-validating institution record','Detecting visual tampering (CV simulation)','Computing fraud risk score','Generating XAI explanation','Saving verification result'];let i=0;const box=document.getElementById('pipeline');box.innerHTML='';const timer=setInterval(()=>{box.innerHTML+=`<div class="pipe"><span class="dot"></span>${steps[i]} — complete</div>`;i++;if(i===steps.length){clearInterval(timer);setTimeout(showResult,400)}},350)}
function showResult(){document.getElementById('progressBox').classList.add('hidden');const cert=document.getElementById('certno').value.trim();const match=records.find(r=>r[0].toLowerCase()===cert.toLowerCase());let risk=match?18:67;let cls=match?'Genuine':'Suspicious';let reason=match?'The certificate number and supplied identity fields match a demonstration institutional reference record. No strong simulated tampering indicator was produced.':'No exact demonstration institutional record match was found. The simulated workflow therefore raises the risk level for manual review.';const el=document.getElementById('resultBox');el.classList.remove('hidden');el.innerHTML=`<h2>Verification Result <span class="tag">SIMULATED</span></h2><div class="result"><div><span class="badge ${cls.toLowerCase()}">${cls}</span><div class="score">${risk}/100</div><p><b>Fraud risk score</b> (demonstration value)</p><h3>XAI explanation</h3><p>${reason}</p><p><b>Cross-validation:</b> ${match?'Match found':'No match found'}<br><b>Visual tampering:</b> ${match?'No simulated anomaly':'Review recommended'}<br><b>OCR:</b> Extracted fields reviewed by user</p><button class="primary" onclick="window.print()">Print / Save Demo Report</button> <button class="secondary" onclick="overrideResult()">Administrator Override</button></div><div><h3>Explanation heatmap</h3><div class="heat">Illustrative XAI heatmap</div><p class="muted">For interface demonstration only; not a real Grad-CAM output.</p></div></div>`;audits.unshift([new Date().toLocaleString(),'SYSTEM',`Verification completed: ${cls} (simulated risk ${risk}/100)`]);render();}
function overrideResult(){const r=prompt('Administrator decision: Genuine, Suspicious, or Forged','Suspicious');if(!r)return;audits.unshift([new Date().toLocaleString(),'Administrator',`Classification overridden to ${r}`]);alert('Demo override saved to the local audit log.');render();}
function addRecord(){const c=prompt('Certificate number');if(!c)return;const s=prompt('Student name')||'Demo Student';const q=prompt('Qualification')||'Demo Qualification';records.push([c,s,q,'Active']);audits.unshift([new Date().toLocaleString(),'Administrator',`Institution record added: ${c}`]);render();}
function render(){document.getElementById('recordRows').innerHTML=records.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('');document.getElementById('auditRows').innerHTML=audits.map(a=>`<tr><td>${a[0]}</td><td>${a[1]}</td><td>${a[2]}</td><td>${a[3]||''}</td></tr>`).join('');}render();
