
const $=s=>document.querySelector(s);
let state={view:"login",scenario:"genuine",file:null,hash:"Not calculated",fields:{name:"Lerato Mokoena",number:"TUT-2026-10482",qualification:"Diploma in Information Technology",institution:"Tshwane University of Technology",date:"2026-05-15"},logs:[
["2026/09/25 01:29:39","AD","Completed verification","TUT-2026-10482","Genuine","Risk: 12/100"],
["2026/09/24 16:11:02","AD","Administrator override","UL-2025-77821","Suspicious","Manual review required"],
["2026/09/24 15:47:18","AD","Completed verification","DEMO-INVALID-01","Forged","Risk: 92/100"]]};
const scenarioData={
genuine:{name:"Lerato Mokoena",number:"TUT-2026-10482",qualification:"Diploma in Information Technology",institution:"Tshwane University of Technology",date:"2026-05-15",risk:12,outcome:"Genuine"},
suspicious:{name:"Thando Ndlovu",number:"UL-2025-77821",qualification:"Bachelor of Information Science",institution:"University of Limpopo",date:"2025-12-10",risk:68,outcome:"Suspicious"},
forged:{name:"Demo Invalid Record",number:"DEMO-INVALID-01",qualification:"Diploma in Information Technology",institution:"Unknown / unmatched institution",date:"2026-03-02",risk:92,outcome:"Forged"}};
function brand(){return `<div class="brand"><div class="shield">◆</div><div>CertiGuard<div style="font-size:11px;font-weight:500;color:#66758f">Academic Certificate Verification System</div></div></div>`}
function login(){return `<div class="login"><section class="hero">${brand()}<h1>Trusted Certificate Verification with Explainable AI</h1><p>Academic certificate verification demonstration combining document review, institutional cross-validation, integrity analysis, risk scoring and explainable evidence.</p><div class="checks">✓ Evidence-led verification workflow<br>✓ Explainable results with evidence<br>✓ Role-based administrator review<br>✓ Traceable audit trail</div></section><section class="login-side"><div class="login-card"><div class="eyebrow">SECURE ACCESS</div><h2>Welcome back</h2><p class="sub">Sign in to the CertiGuard demonstration workspace.</p><label>Email address</label><input id="email" value="administrator@certiguard.demo"><label>Password</label><input type="password" value="CertiGuard2026"><button class="primary wide" onclick="state.view='dashboard';render()">Sign in →</button><p class="sub" style="font-size:12px;text-align:center;margin-top:20px">Demonstration account — no credentials are transmitted.</p></div></section></div>`}
function layout(content,active=""){return `<header class="top">${brand()}<span class="online">● DEMO SYSTEM ONLINE</span></header><div class="shell"><aside>${nav("dashboard","▣ Dashboard",active)}${nav("verify","✓ Verify Certificate",active)}${nav("records","▤ Institution Records",active)}${nav("audit","☷ Audit Trail",active)}${nav("system","ⓘ System Info",active)}<div style="margin-top:300px;padding:12px"><b>AD &nbsp; Administrator</b><div class="sub">Demo workspace</div></div></aside><main class="main">${content}</main></div>`}
function nav(v,t,a){return `<div class="nav ${a===v?"active":""}" onclick="state.view='${v}';render()">${t}</div>`}
function dashboard(){return layout(`<div class="heading"><div><div class="eyebrow">SECURITY OPERATIONS</div><h1>Verification Dashboard</h1><p class="sub">Monitor certificate checks, risk classifications and institutional cross-validation.</p></div><button class="primary" onclick="state.view='verify';render()">+ New Verification</button></div><div class="notice"><b>Demonstration environment.</b> File metadata and SHA-256 fingerprints are computed live in your browser. OCR/CV/XAI outputs are deterministic demonstration outputs and are not experimental model results.</div><div class="cards"><div class="card"><span class="sub">Verification requests</span><div class="metric">4</div>All demo checks</div><div class="card green"><span class="sub">Genuine</span><div class="metric">2</div>Low-risk outcomes</div><div class="card amber"><span class="sub">Suspicious</span><div class="metric">1</div>Manual review</div><div class="card red"><span class="sub">Forged</span><div class="metric">1</div>High-risk outcomes</div></div><div class="grid2"><div class="panel"><div class="eyebrow">PIPELINE</div><h2>Verification workflow</h2><div class="pipeline">${["Upload","OCR","Validate","CV","Risk","XAI","Result"].map((x,i)=>`<div class="stage">${i+1}<br><br>${x}</div>${i<6?"→":""}`).join("")}</div><button class="primary" onclick="state.view='verify';render()">Start certificate check</button></div><div class="panel"><div class="eyebrow">RECENT ACTIVITY</div><h2>Latest checks</h2>${state.logs.slice(0,3).map(x=>`<div class="activity"><div><b>${x[3]}</b><br><span class="sub">${x[2]}</span></div><span class="badge ${x[4].toLowerCase()}">${x[4]}</span></div>`).join("")}</div></div>`,"dashboard")}
function steps(n){return `<div class="steps">${["1 Upload","2 Extract & Review","3 Analyse","4 Result"].map((x,i)=>`<span class="step ${i<n?"on":""}">${x}</span>`).join("")}</div>`}
function verify(){return layout(`<div class="eyebrow">CERTIFICATE ANALYSIS</div><div class="heading"><div><h1>Verify Certificate</h1><p class="sub">Upload a document and follow the evidence through the CertiGuard pipeline.</p></div><button class="secondary" onclick="reset()">↻ Reset</button></div>${steps(1)}<div class="grid2"><div class="panel"><div class="eyebrow">STEP 01</div><h2>Upload certificate</h2><p class="sub">JPG, PNG or PDF. Recommended maximum size: 10 MB.</p><div class="upload"><div><div style="font-size:35px;color:#1765e8">⇧</div><b>Drop or choose certificate</b><br><input id="file" type="file" accept=".jpg,.jpeg,.png,.pdf" onchange="pick(this.files[0])"><div class="sub">Supported formats: JPG, PNG, PDF</div></div></div><button class="primary wide" onclick="analyse()">Analyse Certificate →</button></div><div class="panel"><div class="eyebrow">QUICK DEMO CASES</div><h3>Choose a verification scenario</h3><p class="sub">This determines demonstration OCR/CV/XAI outputs. Your selected file is still fingerprinted live.</p>${["genuine","suspicious","forged"].map(x=>`<div class="scenario" onclick="setScenario('${x}')"><b>${scenarioData[x].outcome}</b><br><span class="sub">Risk demonstration: ${scenarioData[x].risk}/100</span></div>`).join("")}</div></div>`,"verify")}
async function pick(f){if(!f)return;state.file=f;if(crypto.subtle){let b=await f.arrayBuffer();let h=await crypto.subtle.digest("SHA-256",b);state.hash=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}}
function setScenario(s){state.scenario=s;state.fields={...scenarioData[s]};delete state.fields.risk;delete state.fields.outcome;render()}
function analyse(){if(!state.file){alert("Please choose a JPG, PNG or PDF first.");return}state.view="review";render()}
function preview(){if(!state.file)return "";let u=URL.createObjectURL(state.file);return state.file.type==="application/pdf"?`<iframe src="${u}"></iframe>`:`<img src="${u}">`}
function review(){let f=state.fields;return layout(`<h1>Verify Certificate</h1>${steps(2)}<div class="grid2"><div class="panel"><h2>Document preview</h2><div class="preview">${preview()}</div><div class="fields"><div><label>File name</label>${state.file?.name||""}</div><div><label>File size</label>${state.file?(state.file.size/1024/1024).toFixed(2)+" MB":""}</div></div><label>SHA-256</label><div class="hash">${state.hash}</div></div><div class="panel"><div class="eyebrow">STEP 02</div><h2>Extracted certificate fields</h2><div class="notice">REVIEW REQUIRED — demonstration OCR fields are editable before verification.</div>${field("Student name","name",f.name)}${field("Certificate number","number",f.number)}${field("Qualification","qualification",f.qualification)}${field("Institution","institution",f.institution)}${field("Issue date","date",f.date)}<button class="primary wide" onclick="saveFields();state.view='analysing';render();setTimeout(()=>{state.view='result';render()},1200)">Confirm Fields & Run Verification →</button></div></div>`,"verify")}
function field(l,k,v){return `<label>${l}</label><input id="f_${k}" value="${v}">`}
function saveFields(){["name","number","qualification","institution","date"].forEach(k=>state.fields[k]=$("#f_"+k).value)}
function analysing(){return layout(`<h1>Verification analysis</h1>${steps(3)}<div class="panel"><h2>Running evidence pipeline…</h2><div class="pipeline">${["OCR reviewed ✓","Record matching ✓","Identity consistency ✓","Integrity stage ✓","Risk scoring ✓","XAI evidence ✓"].map(x=>`<div class="stage">${x}</div>`).join("→")}</div><p class="sub">Demonstration analysis in progress.</p></div>`,"verify")}
function result(){let d=scenarioData[state.scenario],cls=d.outcome.toLowerCase();let match=d.outcome==="Genuine"?"MATCH":d.outcome==="Suspicious"?"PARTIAL MATCH":"NO MATCH";return layout(`<h1>Verify Certificate</h1>${steps(4)}<div class="resultHero"><div><div class="eyebrow" style="color:white">VERIFICATION OUTCOME</div><h1>${d.outcome}</h1><div>${state.fields.number} · ${state.fields.name}</div></div><div class="risk">${d.risk}<small style="font-size:9px">RISK / 100</small></div></div><div class="grid2"><div class="panel"><div class="eyebrow">EVIDENCE SUMMARY</div><h2>Why this result?</h2><div class="evidence"><b>Institutional cross-validation</b><b>${match}</b></div><div class="evidence"><b>Identity field consistency</b><b>${d.outcome==="Forged"?"INCONSISTENT":"CONSISTENT"}</b></div><div class="evidence"><b>Visual integrity stage</b><b>${d.outcome==="Genuine"?"No strong anomaly (demo)":d.outcome==="Suspicious"?"Review indicators (demo)":"Strong anomaly indicators (demo)"}</b></div><div class="evidence"><b>File fingerprint</b><span>${state.hash.slice(0,18)}…</span></div><div class="actions"><button class="primary" onclick="window.print()">▧ Print / Save Report</button><button class="secondary" onclick="state.view='override';render()">Administrator Override</button><button class="secondary" onclick="state.view='verify';render()">Verify Another</button></div></div><div class="panel"><div class="eyebrow">EXPLAINABLE AI</div><h2>Evidence attention view</h2><div class="heat"></div><p class="sub">Illustrative interface for XAI/Grad-CAM-style output. This is intentionally not presented as measured model evidence in this static demonstration.</p><hr><h3>Verification reference</h3><b>CG-2026-${state.hash.slice(0,8).toUpperCase()}</b><p class="sub">File: ${state.file?.name}<br>Hash: ${state.hash}<br>Checked: ${new Date().toLocaleString()}</p></div></div>`,"verify")}
function override(){let d=scenarioData[state.scenario];return layout(`<div class="eyebrow">ADMINISTRATOR CONTROL</div><h1>Administrator Review</h1><p class="sub">Review the automated demonstration outcome and record a traceable human decision.</p><div class="grid2"><div class="panel"><h3>Original classification</h3><div class="cards" style="grid-template-columns:1fr 1fr"><div class="card red"><b>${d.outcome}</b><div class="metric">${d.risk}/100</div>Risk score</div><div class="card"><b>${state.fields.number}</b><br><br>${state.fields.name}</div></div><h3>Administrator decision</h3>${["Genuine","Suspicious","Forged"].map(x=>`<label><input style="width:auto" type="radio" name="decision" value="${x}" ${x===d.outcome?"checked":""}> Confirm as ${x}</label>`).join("")}</div><div class="panel"><h3>Justification (required)</h3><textarea id="just" rows="8" placeholder="Document the reason for the administrator decision..."></textarea><button class="primary wide" onclick="saveOverride()">Save Decision to Audit Trail</button></div></div>`,"verify")}
function saveOverride(){let j=$("#just").value.trim();if(!j){alert("Please enter an administrator justification.");return}let dec=document.querySelector('input[name=decision]:checked').value;state.logs.unshift([new Date().toLocaleString(),"AD","Administrator override",state.fields.number,dec,j]);state.view="audit";render()}
function audit(){return layout(`<div class="heading"><div><div class="eyebrow">TRACEABILITY</div><h1>Audit Trail</h1><p class="sub">Verification activity, administrator actions and system events.</p></div><button class="secondary" onclick="exportLog()">⇩ Export log</button></div><div class="panel"><table class="table"><thead><tr><th>Date / time</th><th>User</th><th>Action</th><th>Certificate ID</th><th>Outcome</th><th>Details</th></tr></thead><tbody>${state.logs.map(x=>`<tr>${x.map((y,i)=>`<td>${i===4?`<span class="badge ${y.toLowerCase()}">${y}</span>`:y}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`,"audit")}
function records(){return layout(`<div class="eyebrow">REFERENCE DATA</div><h1>Institution Records</h1><p class="sub">Demonstration reference records used to illustrate institutional cross-validation.</p><div class="panel"><table class="table"><tr><th>Certificate ID</th><th>Student</th><th>Qualification</th><th>Institution</th><th>Status</th></tr><tr><td>TUT-2026-10482</td><td>Lerato Mokoena</td><td>Diploma in Information Technology</td><td>Tshwane University of Technology</td><td><span class="badge genuine">Active</span></td></tr><tr><td>UL-2025-77821</td><td>Thando Ndlovu</td><td>Bachelor of Information Science</td><td>University of Limpopo</td><td><span class="badge genuine">Active</span></td></tr></table></div>`,"records")}
function system(){return layout(`<div class="eyebrow">SYSTEM TRANSPARENCY</div><h1>System Information</h1><div class="grid2"><div class="panel"><h2>CertiGuard demonstration</h2><p>This deployment is a browser-based academic prototype designed to demonstrate the complete certificate-verification user journey.</p><h3>Computed live</h3><p>File name, file size, timestamps and SHA-256 fingerprint.</p><h3>Demonstration/simulated</h3><p>OCR field extraction, institutional matching outcomes, CV integrity indicators, fraud-risk score and XAI attention map.</p></div><div class="panel"><h2>Verification pipeline</h2><div class="pipeline">${["Upload","OCR review","Cross-validation","Integrity","Risk","XAI","Human review"].map(x=>`<div class="stage">${x}</div>`).join("")}</div><p class="notice">Do not interpret deterministic demonstration scores as measured model accuracy or experimental findings.</p></div></div>`,"system")}
function exportLog(){let csv="Date,User,Action,Certificate ID,Outcome,Details\n"+state.logs.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="certiguard-audit-log.csv";a.click()}
function reset(){state.file=null;state.hash="Not calculated";state.view="verify";render()}
function render(){let views={login,dashboard,verify,review,analysing,result,override,audit,records,system};$("#app").innerHTML=views[state.view]()}
render();
