const records=[
 {cert:'TUT-2026-10482',student:'Lerato Mokoena',institution:'Tshwane University of Technology',qualification:'Diploma in Information Technology',status:'Active'},
 {cert:'UL-2025-77821',student:'Thabo Ndlovu',institution:'University of Limpopo',qualification:'BSc Computer Science',status:'Active'},
 {cert:'UNIVEN-2024-32017',student:'Naledi Mathonsi',institution:'University of Venda',qualification:'BCom',status:'Active'}
];
const audits=[{time:new Date().toLocaleString(),actor:'SYSTEM',event:'Demo environment initialised',ref:'SESSION'}];
let currentFile=null,currentHash='',scenario='genuine',counts={total:3,genuine:1,suspicious:1,forged:1};
const $=id=>document.getElementById(id);
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));render();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function setStep(n){[1,2,3,4].forEach(i=>$('s'+i).classList.toggle('on',i<=n));}
function fmtBytes(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(2)+' MB'}
function setCase(s){scenario=s;document.querySelectorAll('.demoCases button').forEach(b=>b.classList.remove('selected'));event?.target?.classList.add('selected');const names={genuine:'Genuine reference-match case selected',suspicious:'Suspicious no-match case selected',forged:'Forged/high-risk case selected'};alert(names[s]+'. Now choose any JPG/PNG/PDF to demonstrate the file analysis workflow.');}
function fileSelected(){const f=$('file').files[0];if(!f)return;currentFile=f;$('fileChip').classList.remove('hidden');$('fileChip').innerHTML=`<b>▧ ${escapeHtml(f.name)}</b> · ${fmtBytes(f.size)} · ${escapeHtml(f.type||'unknown type')}`;}
async function sha256(file){const buf=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',buf);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function processFile(){const f=$('file').files[0];if(!f){alert('Please choose a JPG, PNG or PDF certificate first.');return}currentFile=f;currentHash=await sha256(f);$('uploadBox').classList.add('hidden');$('reviewBox').classList.remove('hidden');setStep(2);$('fileType').textContent=(f.type||f.name.split('.').pop()).toUpperCase();$('evSize').textContent=fmtBytes(f.size);$('evHash').textContent=currentHash.slice(0,16)+'…';$('evHash').title=currentHash;$('evModified').textContent=new Date(f.lastModified).toLocaleDateString();$('hashField').value=currentHash;
 const url=URL.createObjectURL(f);$('preview').innerHTML=f.type.startsWith('image/')?`<img src="${url}" alt="Certificate preview">`:f.type==='application/pdf'?`<iframe src="${url}"></iframe>`:`<span>Preview unavailable</span>`;
 const cases={genuine:['Lerato Mokoena','TUT-2026-10482','Diploma in Information Technology','Tshwane University of Technology','2026-05-15'],suspicious:['Lerato Mokoena','TUT-2026-99999','Diploma in Information Technology','Tshwane University of Technology','2026-05-15'],forged:['Unknown Student','CG-ALTERED-009','Doctor of Computing','Unknown Institution','2026-05-15']};
 ['student','certno','qual','inst','date'].forEach((id,i)=>$(id).value=cases[scenario][i]);log('Verification Officer','Certificate uploaded and SHA-256 fingerprint generated',currentHash.slice(0,12));}
function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function runVerification(){if(!$('student').value.trim()||!$('certno').value.trim()){alert('Student name and certificate number are required.');return}$('reviewBox').classList.add('hidden');$('progressBox').classList.remove('hidden');setStep(3);const steps=[['Record cross-validation','Compare certificate fields with institutional reference data'],['Visual integrity check','Demonstrate CV tamper-analysis stage'],['Fraud risk engine','Combine record and integrity indicators'],['XAI evidence','Prepare human-readable explanation'],['Secure result','Create audit event and verification outcome']];$('pipeline').innerHTML=steps.map(s=>`<div class="pipe"><b>${s[0]}</b><small>${s[1]}</small></div>`).join('');let i=0;const timer=setInterval(()=>{document.querySelectorAll('.pipe')[i].classList.add('done');i++;let pct=i*20;$('progressPct').textContent=pct+'%';$('progressBar').style.width=pct+'%';if(i===steps.length){clearInterval(timer);setTimeout(showResult,450)}},420)}
function showResult(){const cert=$('certno').value,student=$('student').value,qual=$('qual').value,inst=$('inst').value;const rec=records.find(r=>norm(r.cert)===norm(cert));const certMatch=!!rec,studentMatch=rec&&norm(rec.student)===norm(student),qualMatch=rec&&norm(rec.qualification)===norm(qual),instMatch=rec&&norm(rec.institution)===norm(inst);const fieldMatches=[certMatch,studentMatch,qualMatch,instMatch].filter(Boolean).length;
 let cls,risk,tamper;if(scenario==='forged'){cls='Forged';risk=91;tamper='High anomaly (demo)'}else if(certMatch&&fieldMatches===4){cls='Genuine';risk=12;tamper='No strong anomaly (demo)'}else{cls='Suspicious';risk=64;tamper='Review recommended (demo)'}
 const recordText=certMatch?`${fieldMatches}/4 supplied fields match the reference record`:'No certificate-number match in the demo reference records';const explanation=cls==='Genuine'?'The institutional record is present and all supplied identity fields match. The demonstration integrity stage did not raise a strong anomaly.':cls==='Suspicious'?'The certificate could not be fully corroborated against the demo institutional records. Manual review is recommended before acceptance.':'The selected high-risk demonstration scenario combines a failed institutional match with a strong simulated integrity warning. Administrator review is required.';
 $('progressBox').classList.add('hidden');setStep(4);$('resultBox').classList.remove('hidden');$('resultBox').innerHTML=`<div class="resultHero ${cls.toLowerCase()}H"><div><span class="eyebrow" style="color:#fff">VERIFICATION OUTCOME</span><h2>${cls}</h2><div>${escapeHtml(cert)} · ${escapeHtml(student)}</div></div><div class="riskring">${risk}<small>RISK / 100</small></div></div><div class="resultgrid"><div class="panel"><div class="panelhead"><div><span class="eyebrow">EVIDENCE SUMMARY</span><h2>Why this result?</h2></div><span class="badge ${cls.toLowerCase()}">${cls}</span></div><p>${explanation}</p><div class="checklist"><div class="check"><p><b>Institutional cross-validation</b><small>${recordText}</small></p><strong class="${certMatch?'pass':'review'}">${certMatch?'MATCH':'NO MATCH'}</strong></div><div class="check"><p><b>Identity field consistency</b><small>${fieldMatches}/4 reference fields aligned</small></p><strong class="${fieldMatches===4?'pass':'review'}">${fieldMatches===4?'CONSISTENT':'REVIEW'}</strong></div><div class="check"><p><b>Visual integrity stage</b><small>Interface demonstration; requires CV backend for measured inference</small></p><strong class="${cls==='Genuine'?'pass':'review'}">${tamper}</strong></div><div class="check"><p><b>File fingerprint</b><small>SHA-256 calculated live from uploaded bytes</small></p><strong class="pass">${currentHash.slice(0,12)}…</strong></div></div><div class="actions"><button class="primary" onclick="printReport()">▧ Print / Save Report</button><button class="ghost" onclick="overrideResult()">Administrator Override</button><button class="ghost" onclick="resetVerify()">Verify Another</button></div></div><div class="panel"><span class="eyebrow">EXPLAINABLE AI</span><h2>Evidence attention view</h2><div class="heatmap"></div><p class="muted">Illustrative interface for Grad-CAM/XAI output. This image is intentionally not presented as measured model evidence in the static demo.</p><hr style="border:0;border-top:1px solid #eaecf0"><h3>Verification reference</h3><p><b>${makeRef()}</b></p><p class="muted">File: ${escapeHtml(currentFile?.name||'—')}<br>Hash: ${currentHash}<br>Checked: ${new Date().toLocaleString()}</p></div></div>`;
 counts.total++;counts[cls.toLowerCase()]++;log('SYSTEM',`Verification completed: ${cls}; risk ${risk}/100 (demo scoring)`,cert);render();}
function makeRef(){return 'CG-'+new Date().getFullYear()+'-'+currentHash.slice(0,8).toUpperCase()}
function printReport(){window.print();log('Verification Officer','Verification report opened for print/save',makeRef());render()}
function overrideResult(){const r=prompt('Administrator decision: Genuine, Suspicious, or Forged','Suspicious');if(!r)return;log('Administrator',`Classification override recorded: ${r}`,$('certno').value);alert('Override recorded in this session audit trail.');render()}
function resetVerify(){$('uploadBox').classList.remove('hidden');$('reviewBox').classList.add('hidden');$('progressBox').classList.add('hidden');$('resultBox').classList.add('hidden');$('file').value='';$('fileChip').classList.add('hidden');$('progressBar').style.width='0';$('progressPct').textContent='0%';setStep(1);currentFile=null;currentHash='';scenario='genuine'}
function addRecord(){const cert=prompt('Certificate number');if(!cert)return;const student=prompt('Student name')||'Demo Student';const institution=prompt('Institution')||'Demo Institution';const qualification=prompt('Qualification')||'Demo Qualification';records.push({cert,student,institution,qualification,status:'Active'});log('Administrator','Institution record added',cert);render()}
function log(actor,event,ref=''){audits.unshift({time:new Date().toLocaleString(),actor,event,ref})}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){$('recordRows').innerHTML=records.map(r=>`<tr><td><b>${escapeHtml(r.cert)}</b></td><td>${escapeHtml(r.student)}</td><td>${escapeHtml(r.institution)}</td><td>${escapeHtml(r.qualification)}</td><td><span class="state">${escapeHtml(r.status)}</span></td></tr>`).join('');$('auditRows').innerHTML=audits.map(a=>`<tr><td>${escapeHtml(a.time)}</td><td><b>${escapeHtml(a.actor)}</b></td><td>${escapeHtml(a.event)}</td><td>${escapeHtml(a.ref)}</td></tr>`).join('');$('mTotal').textContent=counts.total;$('mGenuine').textContent=counts.genuine;$('mSuspicious').textContent=counts.suspicious;$('mForged').textContent=counts.forged}render();
